defaults: &defaults
  working_directory: /tmp/react-swipeable-views
  docker:
    - image: circleci/node:8
restore_repo: &restore_repo
  # The cache logic of CircleCI has been disabled for Security reasons.
  # We can no longer use it.
  # restore_cache:
  #   keys:
  #     - v1-repo-{{ .Branch }}-{{ .Revision }}
  run:
    name: Install js dependencies
    command: yarn
version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - *restore_repo
      - run:
          name: Check versions and env
          command: |
            yarn --version
            node --version
            docker --version
            docker-compose --version
            env
            yarn cache dir
      - restore_cache:
          key: v1-yarn-sha-{{ checksum "yarn.lock" }}
      - run:
          name: Install js dependencies
          command: yarn
      - run:
          name: Should not have any git not staged
          command: git diff --exit-code
      - save_cache:
          key: v1-yarn-sha-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/v1
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - /tmp/react-swipeable-views
  test_unit:
    <<: *defaults
    steps:
      - checkout
      - *restore_repo
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Is the size acceptable?
          command: yarn build && yarn size
      - run:
          name: Tests fake browser
          command: yarn test:coverage
      - run:
          name: Check coverage generated
          command: |
            if ! [[ -s coverage/lcov.info ]]
            then
              exit 1
            fi
      - run:
          name: Coverage
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  pipeline:
    jobs:
      - checkout
      - test_unit:
          requires:
            - checkout
